2 jobs

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,10 +1,20 @@
 name: 01 - Building Blocks
 on: 
   workflow_dispatch:
-  
+
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
       - name: Hello step
         run: echo "Hello, world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail now"
+          exit 1
+      - name: Goodbye step
+        run: |
+          echo "Do widzenia!"
